services:
  traefik:
    image: "traefik"
    restart: unless-stopped
    env_file:
      - .env.minio
    command:
      - "--api=true"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.mytlschallenge.acme.tlschallenge=true"
      - "--certificatesresolvers.mytlschallenge.acme.email=${SSL_EMAIL}"
      - "--certificatesresolvers.mytlschallenge.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_data:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - nca-network

  ncat:
    image: stephengpope/no-code-architects-toolkit:latest
    env_file:
      - .env.minio
    labels:
      - traefik.enable=true
      - traefik.http.routers.ncat.rule=Host(`${APP_DOMAIN}`)
      - traefik.http.routers.ncat.tls=true
      - traefik.http.routers.ncat.entrypoints=web,websecure
      - traefik.http.routers.ncat.tls.certresolver=mytlschallenge
    volumes:
      - storage:/var/www/html/storage/app
      - logs:/var/www/html/storage/logs
    restart: unless-stopped
    depends_on:
      - minio
      - minio-init
    networks:
      - nca-network

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    env_file:
      - .env.minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin123}
    volumes:
      - minio_data:/data
    restart: unless-stopped
    networks:
      - nca-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.minio.rule=Host(`${MINIO_DOMAIN}`)
      - traefik.http.routers.minio.tls=true
      - traefik.http.routers.minio.entrypoints=web,websecure
      - traefik.http.routers.minio.tls.certresolver=mytlschallenge
      - traefik.http.routers.minio.service=minio
      - traefik.http.services.minio.loadbalancer.server.port=9000

  minio-init:
    image: minio/mc:latest
    env_file:
      - .env.minio
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin123};
      /usr/bin/mc mb myminio/${S3_BUCKET_NAME:-nca-toolkit-prod} --ignore-existing;
      /usr/bin/mc anonymous set public myminio/${S3_BUCKET_NAME:-nca-toolkit-prod};
      echo 'MinIO bucket ${S3_BUCKET_NAME:-nca-toolkit-prod} created and configured as public';
      "
    networks:
      - nca-network

volumes:
  traefik_data:
    driver: local
  storage:
    driver: local
  logs:
    driver: local
  minio_data:
    driver: local

networks:
  nca-network:
    driver: bridge